name: aoc2020
version: 0.1.0
synopsis: AoC - Advent of Code 2020
maintainer: Will Czifro
category: cli

ghc-options: -threaded -Wall

dependencies:
  - base >= 4.7 && < 5
  - directory
  - dotenv
  - hpack
  - optparse-applicative
  - path
  - text
  - split

library:
  source-dirs: src
  exposed-modules:
    - AOC2020
    - AOC2020.Day1
    - AOC2020.Day2
    - AOC2020.Day3
    - AOC2020.Day4
    - AOC2020.Day5

executable:
  main: Main.hs
  source-dirs: app
  dependencies:
    - aoc2020

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec
      - QuickCheck
    build-tools: hspec-discover
